### ISSUE TITLE
Add support for adding article references

### ISSUE THREAD

**Issue by JaakkoLipsanen** [ScrumMestarit/BibTeXt#1]
As a user 
I want to add new article references
so that I can easily make new article references

**Tasks:**
- [x] Implement form for adding references
- [x] Implement necessary database according to schema for persistent references
- [x] [Add tests](#17)

**Comment by anttilip** [comment]
Functionality implemented in c82d212. Tests not yet done.

**Comment by impliedfeline** [comment]
Tests merged in #21, closing,
